### ISSUE TITLE
Link text

### ISSUE THREAD

**Issue by lvafi** [victorsalmon/aloha#4]
The text "About" is unclear without context and may be confusing to screen readers. Consider rearranging the <a></a> tags or including special screen reader text.
Relevant code:
`<a href="#about" style="color: rgb(226, 87, 76); background-color: rgba(0, 0, 0, 0);">About</a>
`

**Comment by victorsalmon** [comment]
Thanks for the feedback! I've spoken with the accessibility instructor (Rose) about this warning from the Developer Tools Accountability Extension in Chrome, and while the word about is normally not semantic, in this case it's actually pretty clear because of convention what is meant by the word About. In fact, if you turn on Chrome Vox you can hear the menu read as a nav list of four items, each of which it reads clearly when you tab through them. Please feel free to message me about this warning message if you'd like to discuss it further but I've decided not to change the page at this time. Thanks again for your help improving the site!
